[automation_servers]
automation.local ansible_user=deploy ansible_host=10.0.0.10

[application_servers:children]
dev
staging
production

[dev]
dev-app.local ansible_user=deploy

[staging]
staging-app.local ansible_user=deploy
# staging-app-01.local ansible_host=example.com ansible_user=ubuntu
# staging-app-02.local ansible_host=example.com ansible_user=ubuntu

[production]
#prod-app-01.local ansible_user=deploy
prod-app-02.local ansible_user=deploy
