---
traefik_host: "staging.app.example.com"
traefik_dashboard_host: "dashboard.staging.app.example.com"
www_redirect_host: "www.staging.app.example.com"
traefik_expose_compose_paths: true
app_docker_image_name: "ghcr.io/your-org/your-app"
app_docker_image_tag: "latest"
app_image_pull_policy: "always"
